POST http://localhost:5000/api/places
Content-Type: application/json

{
    "title":"New York Stock Exchange",
    "description":"Where the money lives",
    "creator":"u2",
    "address" : "11 Wall St, New York, NY 11005"
}

###

PATCH  http://localhost:5000/api/places/60d69e2689680135703698a0
Content-Type: application/json

{
    
    "title":"Colombo",
    "description":"Where the money lives"
    
  
}

###

DELETE http://localhost:5000/api/places/60d6b69d4c9cc72594edeaf3
Content-Type: application/json

###

GET http://localhost:5000/api/places/user/u2
Content-Type: application/json

###

GET http://localhost:5000/api/places/60d69e2689680135703698a0
Content-Type: application/json

###

GET http://localhost:5000/api/users
Content-Type: application/json

###

POST http://localhost:5000/api/users/signup
Content-Type: application/json

{
   "name":"Ma",
   "email":"Tes2t@gmail.com",
   "password":"tefafafafa",
   "places":"p1"
}

###

POST http://localhost:5000/api/users/login
Content-Type: application/json

{
   "email":"test@gmail.com",
   "password":"testing"
}
